version: "3"
services:
  server:
    image: luanvv/licode-ssl:0.1
    restart: unless-stopped
    container_name: video-cf-server
    ports:
      - "3000:3000"
      - "3001:3001"
      - "$MIN_PORT-$MAX_PORT:$MIN_PORT-$MAX_PORT/udp"
      - "8080:8080"
    network_mode: "host"
    # networks:
    #   - network
    volumes:
      - project-volume:/opt/licode/
      # - ./cert:/opt/licode/cert
      - /opt/videos:/tmp
    environment:
      SSL: "true"
      MIN_PORT: $MIN_PORT
      MAX_PORT: $MAX_PORT
      PUBLIC_IP: $PUBLIC_IP
      NETWORK_INTERFACE: "eth0"
      BASICEXAMPLE: "false"
  nginx:
    image: nginx:1.19-alpine
    container_name: video-cf-nginx
    restart: unless-stopped
    ports:
      - "443:443"
    depends_on:
      - server
    network_mode: "host"
    # networks:
      # - network
    volumes:
      - ./extras/docker/nginx/templates:/etc/nginx/templates
      - ./cert:/cert
    environment:
        NGINX_ENVSUBST_TEMPLATE_SUFFIX: ".template"
        DOMAIN_NAME: $PUBLIC_IP
  client:
    build:
      context: ./extras/basic_example
    container_name: video-cf-client
    restart: unless-stopped
    depends_on:
      - server
    # networks:
    #   - network
    network_mode: "host"
    command: > 
      bash -c "cp /licode/nuve/nuveClient/dist/nuve.js /app/nuve.js && 
              cp -r /licode/erizo_controller/erizoClient/dist/assets /app/public/ &&
              cp /licode/licode_config.js /app &&
              node basicServer.js"
    volumes:
      - project-volume:/licode/
      - ./cert:/app/cert
volumes:
  project-volume:
# networks:
#   network:
#     driver: bridge
